-------------------------------------------------------------------------------
Test set: mss.cadastroDeUsuarios.CadastroDeUsuariosApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.619 s <<< FAILURE! - in mss.cadastroDeUsuarios.CadastroDeUsuariosApplicationTests
contextLoads  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: mss.cadastroDeUsuarios.adress.Address.address in mss.cadastroDeUsuarios.user.User.addressList
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: mss.cadastroDeUsuarios.adress.Address.address in mss.cadastroDeUsuarios.user.User.addressList

